language: node_js
services:
  - mongodb
before_script:
  - sleep 10
  - mongo jenkings --eval 'db.addUser("jenkings", "kernel");'
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
notifications:
  email: false
  